package classes.keywords

/**
 * 'Backing field' is the 'field' keyword. It uses only
 * in the context of 'setters & getters'.
 * The variable is called 'property' if it has a getter and setter
 * In Kotlin all the variables are 'property' by default
 */

class BackingField {
    // default getter and setter generated by the Kotlin compiler
    var tempVar: String = "String"
        set (value) {field = value}
        get () {return field}
}