package classes.keywords

/**
 * 'Backing field' is the 'field' keyword. It uses only
 * in the context of 'setters & getters'.
 * The variable is called 'property' if it has a getter and setter
 * In Kotlin all the variables are 'property' by default
 */

class BackingField {
    // default getter and setter generated by the Kotlin compiler
    var tempVar: String = "String"
        set (value) {field = value}
        get () {return field}

    // we cannot write like this because 'ex1 = value' calls a setter,
    // so here we call a setter inside another setter, that is why
    // there is 'backing field'
    var ex1: String
        get() = ex1
        set(value) {ex1 = value}

    // that is the correct code
    var ex2: String = "Bob"
        get() = field
        set(value) {ex2 = field}
}